from collections import Counter

from fastapi import FastAPI

from backend.system_health.health_models import RouteAuditResult


REQUIRED_ROUTES = [
    "/health",
    "/status",
    "/market-data/timeframes",
    "/strategy/session",
    "/risk/status",
    "/risk/config",
    "/execution/status",
    "/mt5/status",
    "/mt5/health",
    "/database/status",
    "/ai/status",
    "/news/status",
    "/orchestration/status",
    "/backtesting/status",
    "/replay/status",
    "/streaming/status",
    "/trading-loop/status",
    "/trade-journal/status",
    "/system/status",
    "/system/readiness",
    "/system/safety-scan",
    "/system/routes",
    "/system/phase-report",
    "/institutional/status",
    "/institutional/sweeps/{symbol}",
    "/institutional/latest-sweep/{symbol}",
    "/institutional/high-quality-sweeps/{symbol}",
    "/institutional/fvg/{symbol}",
    "/institutional/fvg/fresh/{symbol}",
    "/institutional/fvg/mitigated/{symbol}",
    "/institutional/fvg/high-quality/{symbol}",
    "/institutional/fvg/latest/{symbol}",
    "/institutional/order-blocks/{symbol}",
    "/institutional/order-blocks/fresh/{symbol}",
    "/institutional/order-blocks/mitigated/{symbol}",
    "/institutional/order-blocks/high-quality/{symbol}",
    "/institutional/order-blocks/latest/{symbol}",
    "/institutional/order-blocks/context/{symbol}",
    "/institutional/breakers/{symbol}",
    "/institutional/breakers/fresh/{symbol}",
    "/institutional/breakers/mitigated/{symbol}",
    "/institutional/breakers/high-quality/{symbol}",
    "/institutional/breakers/latest/{symbol}",
    "/institutional/breakers/context/{symbol}",
    "/institutional/structure-shift/{symbol}",
    "/institutional/structure-shift/bos/{symbol}",
    "/institutional/structure-shift/choch/{symbol}",
    "/institutional/structure-shift/mss/{symbol}",
    "/institutional/structure-shift/latest/{symbol}",
    "/institutional/structure-shift/high-quality/{symbol}",
    "/institutional/structure-shift/context/{symbol}",
    "/institutional/confluence/{symbol}",
    "/institutional/confluence/score/{symbol}",
    "/institutional/confluence/explanation/{symbol}",
    "/institutional/confluence/components/{symbol}",
    "/institutional/confluence/readiness/{symbol}",
    "/institutional/alignment/{symbol}",
    "/institutional/alignment/narrative/{symbol}",
    "/institutional/alignment/conflicts/{symbol}",
    "/institutional/alignment/timeframes/{symbol}",
    "/institutional/session/{symbol}",
    "/institutional/session/ranges/{symbol}",
    "/institutional/session/killzone/{symbol}",
    "/institutional/session/liquidity/{symbol}",
    "/institutional/session/manipulation/{symbol}",
    "/institutional/session/readiness/{symbol}",
    "/institutional/entry-models/{symbol}",
    "/institutional/entry-models/best/{symbol}",
    "/institutional/entry-models/ready/{symbol}",
    "/institutional/entry-models/waiting/{symbol}",
    "/institutional/entry-models/avoided/{symbol}",
    "/institutional/entry-models/explanation/{symbol}",
    "/institutional/setup-validation/{symbol}",
    "/institutional/setup-validation/approved/{symbol}",
    "/institutional/setup-validation/waiting/{symbol}",
    "/institutional/setup-validation/rejected/{symbol}",
    "/institutional/setup-validation/best/{symbol}",
    "/institutional/setup-validation/readiness/{symbol}",
    "/institutional/simulation-decision/{symbol}",
    "/institutional/simulation-decision/action/{symbol}",
    "/institutional/simulation-decision/intent/{symbol}",
    "/institutional/simulation-decision/explanation/{symbol}",
    "/institutional/simulation-decision/readiness/{symbol}",
    "/institutional/paper-trades/{symbol}",
    "/institutional/paper-trades/candidates/{symbol}",
    "/institutional/paper-trades/active/{symbol}",
    "/institutional/paper-trades/closed/{symbol}",
    "/institutional/paper-trades/latest/{symbol}",
    "/institutional/paper-trades/summary/{symbol}",
    "/institutional/position-management/{symbol}",
    "/institutional/position-management/active/{symbol}",
    "/institutional/position-management/exits/{symbol}",
    "/institutional/position-management/emergency/{symbol}",
    "/institutional/position-management/state/{symbol}",
    "/institutional/position-management/context/{symbol}",
    "/institutional/orchestration/{symbol}",
    "/institutional/orchestration/state/{symbol}",
    "/institutional/orchestration/report/{symbol}",
    "/institutional/orchestration/summary/{symbol}",
    "/institutional/orchestration/health/{symbol}",
    "/institutional/reasoning/{symbol}",
    "/institutional/reasoning/narrative/{symbol}",
    "/institutional/reasoning/summary/{symbol}",
    "/institutional/reasoning/dashboard/{symbol}",
    "/institutional/reasoning/quality/{symbol}",
    "/institutional/performance/{symbol}",
    "/institutional/performance/setups/{symbol}",
    "/institutional/performance/decisions/{symbol}",
    "/institutional/performance/paper-trades/{symbol}",
    "/institutional/performance/position-management/{symbol}",
    "/institutional/performance/recommendations/{symbol}",
    "/institutional/dashboard/{symbol}",
    "/institutional/dashboard/cards/{symbol}",
    "/institutional/dashboard/alerts/{symbol}",
    "/institutional/dashboard/recommendation/{symbol}",
    "/institutional/dashboard/status/{symbol}",
    "/institutional/phase2/status",
    "/institutional/phase2/readiness",
    "/institutional/phase2/safety-audit",
    "/institutional/phase2/completion-report",
    "/institutional/phase2/modules",
    "/institutional/demo/{symbol}",
    "/institutional/demo/summary/{symbol}",
    "/institutional/demo/modules/{symbol}",
    "/institutional/demo/talking-points/{symbol}",
]


class RouteAuditor:
    """Validate the stable API surface without calling application services."""

    def __init__(self, app: FastAPI) -> None:
        self.app = app

    def audit(self) -> RouteAuditResult:
        routes = list(self.app.routes)
        paths = {route.path for route in routes}
        missing = sorted(set(REQUIRED_ROUTES) - paths)
        operation_keys: list[str] = []
        for route in routes:
            methods = getattr(route, "methods", None)
            if methods:
                operation_keys.extend(f"{method} {route.path}" for method in methods)
            else:
                operation_keys.append(f"WEBSOCKET {route.path}")
        duplicates = sorted(key for key, count in Counter(operation_keys).items() if count > 1)
        return RouteAuditResult(
            total_routes=len(routes),
            required_routes=REQUIRED_ROUTES,
            missing_routes=missing,
            duplicate_paths=duplicates,
            passed=not missing and not duplicates,
        )
